### ISSUE TITLE
Recipe does not exists 

### ISSUE THREAD

**Issue by RicardoR** [RicardoR/recipes#28]
After trying to go a non existing recibe the application crash and user only see a black window.
Thanks Javier

**Comment by javitid** [comment]
![Screenshot_20211219-195510](https://user-images.githubusercontent.com/5024097/146687354-542e9815-8c31-4a19-b2e7-a1c2ca15d1f1.jpg)

**Comment by RicardoR** [comment]
Fixed: https://github.com/RicardoR/recipes/commit/5e78d07a295fd95644044297768f964910e2cd2c
